/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package e.sante;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;

/**
 *
 * @author gggggg
 */
public class AlertDialog extends javax.swing.JDialog {

    /**
     * Creates new form AlertDialog
     */
     public AlertDialog(JFrame parent, String message, String title) {
        super(parent, title, true);

        // Set the layout for the panel
        JPanel panel = new JPanel();
        panel.setLayout(new BorderLayout());
        panel.setBackground(new Color(255, 255, 255)); // White background for alert box

        // Title panel with red color and icon
        JPanel titlePanel = new JPanel();
        titlePanel.setBackground(new Color(255, 0, 0)); // Red background for the title bar
        JLabel titleLabel = new JLabel(" " + title);
        titleLabel.setForeground(Color.WHITE);
        titleLabel.setFont(new Font("Arial", Font.BOLD, 14));
        titlePanel.add(titleLabel);

        // Message label in the center of the dialog
        JLabel messageLabel = new JLabel("<html><div style='text-align:center'>" + message + "</div></html>", JLabel.CENTER);
        messageLabel.setFont(new Font("Arial", Font.PLAIN, 14));


        // Button to close the alert
        JPanel buttonPanel = new JPanel();
        buttonPanel.setLayout(new FlowLayout(FlowLayout.CENTER));
        JButton closeButton = new JButton("OK");
        closeButton.setBackground(new Color(255, 0, 0)); // Red button
        closeButton.setForeground(Color.WHITE);
        closeButton.setFocusPainted(false);
        closeButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                dispose();
            }
        });

        buttonPanel.add(closeButton);

        // Add components to the main panel
        panel.add(titlePanel, BorderLayout.NORTH);
        panel.add(messageLabel, BorderLayout.CENTER);
        panel.add(buttonPanel, BorderLayout.SOUTH);

        // Set properties of the dialog box
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.setSize(250, 150);  // Adjust the size
        this.setLocationRelativeTo(parent);  // Center it relative to the main window
        this.setUndecorated(true);  // Remove the default window frame for a custom look
        this.add(panel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     public static void showAlert(JFrame parent, String message, String title) {
        AlertDialog alertDialog = new AlertDialog(parent, message, title);
        alertDialog.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
